spring.application.name=Eventop

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/eventop_db
spring.datasource.username=eventop_user
spring.datasource.password=123456

# Tamaño máximo del pool
spring.datasource.hikari.maximum-pool-size=5
# Número mínimo de conexiones inactivas.
spring.datasource.hikari.minimum-idle=5
# Tiempo maximo en milisegundos que el cliente esperara por una conexion del pool
spring.datasource.hikari.connection-timeout=30000
# Tiempo maximo que una conexion puede permanecer inactiva antes de ser cerrada
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.driver-class-name=org.postgresql.Driver


#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
#logging.level.com.zaxxer.hikari=DEBUG

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# SEGURIDAD
#Parámetros de seguridad
security.jwt.token.secret-key=pQKOkAZ8j59Kb6QJC+LHL7viCOUvfhBZ7PjGeIznKbY=
#Tiempo de expiración del JWT en minutos
security.jwt.token.expire-length=480
